name: "Hello World"
description: "Greet someone"

inputs:
  package:
    description: "Package to upload to the vcpkg registry"
    required: true
  package_version:
    description: "Version of the package"
    required: true

  registry:
    description: "vcpkg target registry (owner/repository)"
    required: true
  app_id:
    description: "SSH Key to use for deployment"
    required: true
  app_key:
    description: "SSH Key to use for deployment"
    required: true

runs:
  using: "composite"
  steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.app_key }}

    - name: Clone registry
      uses: actions/checkout@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        repository: ${{ inputs.registry }}
        path: "vcpkg-registry"

    # Add Portfile

    # Add vcpkg.json

    # Commit updated port
    - name: Commit port
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        mkdir -p ports/${{ inputs.package }}
        touch ports/${{ inputs.package }}/some_file
        git add ports/${{ inputs.package }}
        git commit -m "[${{ inputs.package }}] new port"
      working-directory: "vcpkg-registry"
      shell: bash

    # Get tree identifier for port
    - name: Get git-tree
      id: get-git-tree
      # run: echo "::set-output name=rev::`git rev-parse HEAD:ports/${{ inputs.package }}`"
      run: echo "::set-output name=rev::`LEO`"
      working-directory: "vcpkg-registry"
      shell: bash

    # Add to baseline

    # Add to versions
    - name: Create versions file for the port
      run: |
        INITIAL=`echo ${{ inputs.package }} | cut -c 1-2`
        mkdir -p versions/$INITIAL-
        echo '{"versions": 
        [
          {
            "version": "1.0.0",
            "git-tree": "${{ steps.get-git-tree.outputs.rev }}"
          }
        ]
        }'' >> versions/$INITIAL-/${{ inputs.package }}.json
      working-directory: "vcpkg-registry"
      shell: bash

    # Commit versions
    - name: Commit all
      run: |
        git add versions
        git commit -m "Test"
      # git commit --amend --no-edit
      working-directory: "vcpkg-registry"
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        path: "vcpkg-registry"
        token: ${{ steps.generate-token.outputs.token }}
        base: main
        commit-message: "[Automated] Update port for ${{ inputs.package }} ${{inputs.package_version}}"
        branch: "port-update/${{ inputs.package }}/${{inputs.package_version}}"
        title: "[Automated] Update port for ${{ inputs.package }} ${{inputs.package_version}}"
        delete-branch: true
