name: "Hello World"
description: "Greet someone"

inputs:
  package:
    description: "Package to upload to the vcpkg registry"
    required: true
  package_version:
    description: "Version of the package"
    required: true

  registry:
    description: "vcpkg target registry (owner/repository)"
    required: true
  app_id:
    description: "SSH Key to use for deployment"
    required: true
  app_key:
    description: "SSH Key to use for deployment"
    required: true

runs:
  using: "composite"
  steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.app_key }}

    - name: Clone registry
      uses: actions/checkout@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        repository: ${{ inputs.registry }}
        path: "vcpkg-registry"

    - name: Do some changes
      run: echo "Leo" >> tttt
      working-directory: "vcpkg-registry"
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        path: "vcpkg-registry"
        token: ${{ steps.generate-token.outputs.token }}
        base: main
        commit-message: "[Automated] Update port for ${{ inputs.package }} ${{inputs.package_version}}"
        branch: "port-update/${{ inputs.package }}/${{inputs.package_version}}"
        title: "[Automated] Update port for ${{ inputs.package }} ${{inputs.package_version}}"
        delete-branch: true
