name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  registry:  # id of input
    description: 'Registry repo (owner/repo)'
    required: true
  token:  # id of input
    description: 'Git user token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'