name: "Hello World"
description: "Greet someone"
inputs:
  registry:
    description: "vcpkg target registry (owner/repository)"
    required: true
  deployment_key:
    description: "SSH Key to use for deployment"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.registry }}
        ssh-key: ${{ inputs.deployment_key }}
        path: "vcpkg-registry"

    - run: |
        echo "Test" >> tttt
        git add .
        git commit -m "Update port files"
        git push
      shell: bash
      working-directory: "vcpkg-registry"
