name: "Hello World"
description: "Greet someone"

inputs:
  package:
    description: "Package to upload to the vcpkg registry"
    required: true
  package_version:
    description: "Version of the package"
    required: true
  package_dependencies_path:
    description: "Path toward the vcpkg.json file of the package"
    required: true
  portfile_path:
    description: "Path toward the portfile.cmake file of the package"
    required: true

  registry:
    description: "vcpkg target registry (owner/repository)"
    required: true
  app_id:
    description: "SSH Key to use for deployment"
    required: true
  app_key:
    description: "SSH Key to use for deployment"
    required: true

runs:
  using: "composite"
  steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.app_key }}

    - name: Clone registry
      uses: actions/checkout@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        repository: ${{ inputs.registry }}
        path: "vcpkg-registry"

    # Add vcpkg.json
    - name: Add vcpkg.json
      run: |
        mkdir -p vcpkg-registry/ports/${{ inputs.package }}
        cp ${{ inputs.package_dependencies_path }} vcpkg-registry/ports/${{ inputs.package }}/vcpkg.json
        cp ${{ inputs.portfile_path }} vcpkg-registry/ports/${{ inputs.package }}/portfile.cmake
      shell: bash

    # Commit updated port
    - name: Commit port
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ports/${{ inputs.package }}
        git commit -m "[${{ inputs.package }}] new port"
      working-directory: "vcpkg-registry"
      shell: bash

    # Get tree identifier for port
    - name: Get git-tree
      id: get-git-tree
      run: echo "::set-output name=rev::`git rev-parse HEAD:ports/${{ inputs.package }}`"
      working-directory: "vcpkg-registry"
      shell: bash

    # Add to baseline
    - name: Update baseline
      run: |
        echo '{
          "default": {
            "${{ inputs.package }}": { "baseline": "${{inputs.package_version}}", "port-version": 0 }
          }
        }' >> /tmp/baseline.json
        jq -rs '.[1] * .[0]' versions/baseline.json /tmp/baseline.json >> versions/baseline.json
      shell: bash
      working-directory: "vcpkg-registry"

    # Add to versions
    - name: Create versions file for the port
      run: |
        INITIAL=`echo ${{ inputs.package }} | cut -c 1-1`
        mkdir -p versions/$INITIAL-
        echo '{
          "versions": [
            {
              "version": "${{inputs.package_version}}",
              "git-tree": "${{ steps.get-git-tree.outputs.rev }}"
            }
          ]
        }' >> versions/$INITIAL-/${{ inputs.package }}.json
      working-directory: "vcpkg-registry"
      shell: bash

    # Commit versions
    - name: Commit all
      run: |
        git add versions
        git commit --amend --no-edit
      working-directory: "vcpkg-registry"
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        path: "vcpkg-registry"
        token: ${{ steps.generate-token.outputs.token }}
        base: main
        commit-message: "[Automated] Update port for ${{ inputs.package }} ${{inputs.package_version}}"
        branch: "port-update/${{ inputs.package }}/${{inputs.package_version}}"
        title: "[Automated] Update port for ${{ inputs.package }} ${{inputs.package_version}}"
        delete-branch: true
