name: "Hello World"
description: "Greet someone"
inputs:
  package:
    description: "Package to upload to the vcpkg registry"
    required: true
  registry:
    description: "vcpkg target registry (owner/repository)"
    required: true
  deployment_key:
    description: "SSH Key to use for deployment"
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone registry
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.registry }}
        ssh-key: ${{ inputs.deployment_key }}
        path: "vcpkg-registry"

    - name: Do some changes
      run: echo "Leo" >> tttt
      working-directory: "vcpkg-registry"
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        path: "vcpkg-registry"
        base: main
        commit-message: "[Automated] Update port for ${{ inputs.package }}"
        branch: "update/${{ inputs.package }}/version"
        title: "[Automated] Update port for ${{ inputs.package }}"
        delete-branch: true
