name: "Hello World"
description: "Greet someone"
inputs:
  package:
    description: "Package to upload to the vcpkg registry"
    required: true
  registry:
    description: "vcpkg target registry (owner/repository)"
    required: true
  deployment_key:
    description: "SSH Key to use for deployment"
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone registry
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.registry }}
        ssh-key: ${{ inputs.deployment_key }}
        path: "vcpkg-registry"

    - name: Do some changes
      run: echo "Leo" >> tttt
      working-directory: "vcpkg-registry"
      shell: bash

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout -b "update/${{ inputs.package }}/version"
        git commit -m "Add changes" -a
        git push -u origin "update/${{ inputs.package }}/version"
      shell: bash
      working-directory: "vcpkg-registry"
