on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Does stuff
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Hello world action step
        id: hello
        uses: Yuki-cpp/test-action@main
        with:
          package_version: 3.0.3
          registry: Yuki-cpp/test-vcpkg
          app_id: ${{ secrets.APP_ID }}
          app_key: ${{ secrets.APP_PRIVATE_KEY }}
          package: whatever
          package_dependencies_path: $GITHUB_WORKSPACE/package.json
