on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Does stuff
    steps:
      - name: Hello world action step
        id: hello
        uses: Yuki-cpp/test-action@main
        with:
          registry: Yuki-cpp/test-vcpkg
          deployment_key: ${{ secrets.DEPLOY_KEY }}
          token: ${{ secrets.DEPLOY_KEY }}
          app_id: ${{ secrets.APP_ID }}
          app_key: ${{ secrets.APP_PRIVATE_KEY }}
          package: whatever
