on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Does stuff
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Hello world action step
        id: hello
        uses: Yuki-cpp/test-action@main
        with:
          registry: cpp-playground/upload-to-vcpkg-registry
          registry_access_token:  ${{ steps.generate-token.outputs.token }}
          package_name: super-pkg
          package_version: 1.0.0
          package_dep_file: $GITHUB_WORKSPACE/package.json
          package_port_file: $GITHUB_WORKSPACE/portfile.cmake
